// Generated by CoffeeScript 1.7.1
angular.module('oxChartSamples.controllers', []);

angular.module('oxChartSamples.directives', []);

angular.module('oxChartSamples.services', []);

angular.module('oxChartSamples.filters', []);
