'use strict';

angular.module('oxChartSamples', [
    'ngCookies',
    'ngResource',
    'ngSanitize',
    'ui.router',
    'oxChartSamples.controllers',
    'oxChartSamples.directives',
    'oxChartSamples.services',
    'oxChartSamples.filters',
    'pascalprecht.translate'
])
    .config(['$stateProvider', '$urlRouterProvider', '$translateProvider',
        function($stateProvider, $urlRouterProvider, $translateProvider) {
            $urlRouterProvider.otherwise('/');
            $stateProvider
                .state('home', {
                    url: '/',
                    templateUrl: 'views/home.html',
                    controller: "MainCtrl"
                });
        }
    ]);
// Generated by CoffeeScript 1.7.1
angular.module('oxChartSamples.controllers', []);

angular.module('oxChartSamples.directives', []);

angular.module('oxChartSamples.services', []);

angular.module('oxChartSamples.filters', []);

// Generated by CoffeeScript 1.7.1
angular.module('oxChartSamples.controllers', ['$scope', function() {}]);
